name: Generate History Pages

on:
  push:
    paths:
      - 'docs/stable-list.json'
      - 'docs/release-list.json'
  workflow_dispatch:

jobs:
  generate-history-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate Stable History Page
        env:
          GITHUB_TOKEN: ${{ secrets.HACKCRAFT2_PAT }}  # hackCraft2リポジトリ用のPAT
          TARGET_REPO: "masafumi-t/hackCraft2"  # 対象リポジトリ
        run: |
          # HTMLヘッダーを生成
          cat > docs/stable-history.html << EOF
          <!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>HackCraft2 Stable Build History</title>
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
                  .release { border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }
                  .release:hover { background-color: #f8f9fa; }
                  .release-header { display: flex; justify-content: space-between; align-items: center; }
                  .release-title { font-size: 1.2em; font-weight: bold; }
                  .release-date { color: #666; }
                  .release-body { margin-top: 10px; white-space: pre-wrap; }
                  .release-meta { margin-top: 10px; font-size: 0.9em; color: #666; }
                  .commit-info { margin-top: 10px; padding: 10px; background-color: #f8f9fa; border-radius: 3px; }
                  a { color: #0366d6; text-decoration: none; }
                  a:hover { text-decoration: underline; }
                  .download-link { display: inline-block; margin-top: 10px; padding: 5px 10px; background-color: #28a745; color: white; border-radius: 3px; }
                  .download-link:hover { background-color: #218838; text-decoration: none; }
              </style>
          </head>
          <body>
              <h1>HackCraft2 Stable Build History</h1>
              <div class="releases">
          EOF

          # stable-list.jsonを読み込んで各リリースの情報を取得
          RELEASES=$(cat docs/stable-list.json | jq -r '.releases | reverse | .[]')
          echo "$RELEASES" | while read -r release; do
            if [ -n "$release" ]; then
              JSON_FILE=$(echo "$release" | jq -r '.name')
              if [ -f "docs/downloads/latest/$JSON_FILE" ]; then
                RELEASE_INFO=$(cat "docs/downloads/latest/$JSON_FILE")
                COMMIT_HASH=$(echo "$RELEASE_INFO" | jq -r '.latest.commit_hash')
                
                # GitHub APIを使用してコミット情報を取得
                COMMIT_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/$TARGET_REPO/commits/$COMMIT_HASH")
                
                COMMIT_MESSAGE=$(echo "$COMMIT_INFO" | jq -r '.commit.message')
                COMMIT_DATE=$(echo "$COMMIT_INFO" | jq -r '.commit.author.date')
                COMMIT_URL=$(echo "$COMMIT_INFO" | jq -r '.html_url')
                
                # リリース情報をHTMLに追加
                cat >> docs/stable-history.html << EOF
                <div class="release">
                    <div class="release-header">
                        <div class="release-title">$(echo "$RELEASE_INFO" | jq -r '.latest.name')</div>
                        <div class="release-date">$(echo "$RELEASE_INFO" | jq -r '.latest.published_at')</div>
                    </div>
                    <div class="release-body">$(echo "$RELEASE_INFO" | jq -r '.latest.body')</div>
                    <div class="release-meta">
                        <div>Paper Version: $(echo "$RELEASE_INFO" | jq -r '.latest.paper_version')</div>
                        <div class="commit-info">
                            <strong>Commit:</strong> <a href="$COMMIT_URL" target="_blank">$COMMIT_HASH</a><br>
                            <strong>Message:</strong> $COMMIT_MESSAGE<br>
                            <strong>Date:</strong> $COMMIT_DATE
                        </div>
                    </div>
                    <a href="$(echo "$RELEASE_INFO" | jq -r '.latest.assets[0].browser_download_url')" class="download-link">Download</a>
                </div>
                EOF
              fi
            fi
          done

          # HTMLフッターを追加
          cat >> docs/stable-history.html << EOF
              </div>
          </body>
          </html>
          EOF

      - name: Generate Release History Page
        env:
          GITHUB_TOKEN: ${{ secrets.HACKCRAFT2_PAT }}  # hackCraft2リポジトリ用のPAT
          TARGET_REPO: "masafumi-t/hackCraft2"  # 対象リポジトリ
        run: |
          # HTMLヘッダーを生成
          cat > docs/release-history.html << EOF
          <!DOCTYPE html>
          <html lang="ja">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>HackCraft2 Release History</title>
              <style>
                  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif; max-width: 1200px; margin: 0 auto; padding: 20px; }
                  .release { border: 1px solid #ddd; margin: 10px 0; padding: 15px; border-radius: 5px; }
                  .release:hover { background-color: #f8f9fa; }
                  .release-header { display: flex; justify-content: space-between; align-items: center; }
                  .release-title { font-size: 1.2em; font-weight: bold; }
                  .release-date { color: #666; }
                  .release-body { margin-top: 10px; white-space: pre-wrap; }
                  .release-meta { margin-top: 10px; font-size: 0.9em; color: #666; }
                  .commit-info { margin-top: 10px; padding: 10px; background-color: #f8f9fa; border-radius: 3px; }
                  .version-badge { display: inline-block; padding: 2px 6px; background-color: #0366d6; color: white; border-radius: 3px; font-size: 0.9em; }
                  a { color: #0366d6; text-decoration: none; }
                  a:hover { text-decoration: underline; }
                  .download-link { display: inline-block; margin-top: 10px; padding: 5px 10px; background-color: #28a745; color: white; border-radius: 3px; }
                  .download-link:hover { background-color: #218838; text-decoration: none; }
              </style>
          </head>
          <body>
              <h1>HackCraft2 Release History</h1>
              <div class="releases">
          EOF

          # release-list.jsonを読み込んで各リリースの情報を取得
          RELEASES=$(cat docs/release-list.json | jq -r '.releases | reverse | .[]')
          echo "$RELEASES" | while read -r release; do
            if [ -n "$release" ]; then
              JSON_FILE=$(echo "$release" | jq -r '.name')
              if [ -f "docs/downloads/releases/$JSON_FILE" ]; then
                RELEASE_INFO=$(cat "docs/downloads/releases/$JSON_FILE")
                COMMIT_HASH=$(echo "$RELEASE_INFO" | jq -r '.latest.commit_hash')
                VERSION=$(echo "$release" | jq -r '.version')
                
                # GitHub APIを使用してコミット情報を取得
                COMMIT_INFO=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
                  "https://api.github.com/repos/$TARGET_REPO/commits/$COMMIT_HASH")
                
                COMMIT_MESSAGE=$(echo "$COMMIT_INFO" | jq -r '.commit.message')
                COMMIT_DATE=$(echo "$COMMIT_INFO" | jq -r '.commit.author.date')
                COMMIT_URL=$(echo "$COMMIT_INFO" | jq -r '.html_url')
                
                # リリース情報をHTMLに追加
                cat >> docs/release-history.html << EOF
                <div class="release">
                    <div class="release-header">
                        <div class="release-title">
                            $(echo "$RELEASE_INFO" | jq -r '.latest.name')
                            <span class="version-badge">$VERSION</span>
                        </div>
                        <div class="release-date">$(echo "$RELEASE_INFO" | jq -r '.latest.published_at')</div>
                    </div>
                    <div class="release-body">$(echo "$RELEASE_INFO" | jq -r '.latest.body')</div>
                    <div class="release-meta">
                        <div>Paper Version: $(echo "$RELEASE_INFO" | jq -r '.latest.paper_version')</div>
                        <div class="commit-info">
                            <strong>Commit:</strong> <a href="$COMMIT_URL" target="_blank">$COMMIT_HASH</a><br>
                            <strong>Message:</strong> $COMMIT_MESSAGE<br>
                            <strong>Date:</strong> $COMMIT_DATE
                        </div>
                    </div>
                    <a href="$(echo "$RELEASE_INFO" | jq -r '.latest.assets[0].browser_download_url')" class="download-link">Download</a>
                </div>
                EOF
              fi
            fi
          done

          # HTMLフッターを追加
          cat >> docs/release-history.html << EOF
              </div>
          </body>
          </html>
          EOF

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/stable-history.html docs/release-history.html
          git commit -m "Update history pages" || exit 0
          git push 