name: Generate Release Lists

on:
  push:
    paths:
      - 'docs/release.json'
  workflow_dispatch:

jobs:
  generate-release-lists:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.HACKCRAFT2_PAT }}  # hackCraft2リポジトリ用のPAT
      TARGET_REPO: "masafumi-t/hackCraft2"  # 対象リポジトリ
    steps:
      - uses: actions/checkout@v4

      - name: Copy release.json to downloads
        run: |
          # release.jsonの内容を読み込む
          RELEASE_JSON=$(cat docs/release.json)
          JAR_FILENAME=$(echo "$RELEASE_JSON" | jq -r '.latest.assets[0].name')
          
          # 同名のJSONファイルを作成
          cp docs/release.json "docs/downloads/releases/${JAR_FILENAME%.jar}.json"

      - name: Update release-list.json
        run: |
          # 既存のrelease-list.jsonを読み込む
          if [ -f "docs/release-list.json" ]; then
            cp docs/release-list.json release-list.json
          else
            echo '{"releases": []}' > release-list.json
          fi
          
          # 最新のrelease.jsonの内容を取得
          RELEASE_JSON=$(cat docs/release.json)
          JAR_FILENAME=$(echo "$RELEASE_JSON" | jq -r '.latest.assets[0].name')
          JSON_FILENAME="${JAR_FILENAME%.jar}.json"
          SIZE=$(echo "$RELEASE_JSON" | jq -r '.latest.assets[0].size')
          DATE=$(echo "$RELEASE_JSON" | jq -r '.latest.published_at')
          VERSION=$(echo "$JAR_FILENAME" | grep -o "R[0-9]\+-[a-z0-9]\+" || echo "")
          
          # 新しいエントリを追加
          jq --arg name "$JSON_FILENAME" \
             --arg url "downloads/releases/$JSON_FILENAME" \
             --arg size "$SIZE" \
             --arg date "$DATE" \
             --arg version "$VERSION" \
             '.releases += [{"name": $name, "url": $url, "size": ($size|tonumber), "version": $version, "published_at": $date}]' \
             release-list.json > docs/release-list.json

      - name: Commit and Push Changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add docs/release-list.json "docs/downloads/releases/*.json"
          git commit -m "Update release lists and JSON files" || exit 0
          git push 