name: pages-deploy

on:
  repository_dispatch:
    types: [release_published, release_edited]  # hackCraft2からのリリースイベント
  workflow_dispatch:  # 手動実行も可能に

permissions:
  contents: read
  pages: write
  id-token: write

# 環境保護ルールの設定
environment:
  name: github-pages
  url: ${{ steps.deployment.outputs.page_url }}

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit information
        id: commit
        run: |
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "commit_date=$(git log -1 --format=%cd --date=format:'%Y/%m/%d')" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "commit_author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT

      - name: Create commit info JSON
        run: |
          cat > docs/commit-info.json << EOF
          {
            "hash": "${{ steps.commit.outputs.commit_hash }}",
            "date": "${{ steps.commit.outputs.commit_date }}",
            "message": "${{ steps.commit.outputs.commit_message }}",
            "author": "${{ steps.commit.outputs.commit_author }}"
          }
          EOF

      - name: Get GitHub Releases
        id: releases
        uses: actions/github-script@v7
        with:
          script: |
            // デバッグ情報の出力
            console.log('Fetching releases...');
            
            const releases = await github.rest.repos.listReleases({
              owner: '0x48lab',  // hackCraft2のオーナー
              repo: 'hackCraft2'  // hackCraft2のリポジトリ名
            });
            
            console.log('Found releases:', releases.data.map(r => r.tag_name));
            
            const releaseData = releases.data.map(release => ({
              tag_name: release.tag_name,
              name: release.name,
              published_at: release.published_at,
              body: release.body,
              assets: release.assets.map(asset => ({
                name: asset.name,
                size: asset.size,
                download_count: asset.download_count,
                browser_download_url: asset.browser_download_url
              }))
            }));

            // リリースを分類
            const stableReleases = releaseData.filter(r => r.tag_name.startsWith('stable-'))
              .sort((a, b) => {
                const numA = parseInt(a.tag_name.split('-')[1]);
                const numB = parseInt(b.tag_name.split('-')[1]);
                return numB - numA; // 降順（新しい順）
              });

            // 最新のstableリリース
            const latestStable = stableReleases[0];
            console.log('Latest stable release:', latestStable?.tag_name);
            
            // リリース情報をJSONファイルとして保存
            const fs = require('fs');
            const releasesPath = 'docs/releases.json';
            const latestPath = 'docs/latest-release.json';
            
            try {
              fs.writeFileSync(releasesPath, JSON.stringify(releaseData, null, 2));
              fs.writeFileSync(latestPath, JSON.stringify(latestStable, null, 2));
              console.log('Successfully wrote release data to:', releasesPath, 'and', latestPath);
              
              // ファイルが実際に作成されたか確認
              if (fs.existsSync(releasesPath) && fs.existsSync(latestPath)) {
                console.log('Files exist after writing');
                console.log('releases.json size:', fs.statSync(releasesPath).size);
                console.log('latest-release.json size:', fs.statSync(latestPath).size);
              } else {
                console.log('Error: Files do not exist after writing');
              }
            } catch (error) {
              console.error('Error writing release data:', error);
              throw error;
            }

      - name: List generated files
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo "\nContents of releases.json:"
          cat docs/releases.json
          echo "\nContents of latest-release.json:"
          cat docs/latest-release.json

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Add cache control headers
        run: |
          cat > docs/_headers << EOF
          /*
            Cache-Control: no-cache, no-store, must-revalidate
            Pragma: no-cache
            Expires: 0
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 