name: pages-deploy

on:
  repository_dispatch:
    types: [release_published, release_edited]  # hackCraft2からのイベント
  workflow_dispatch:  # 手動実行用

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get commit information
        id: commit
        run: |
          echo "commit_hash=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
          echo "commit_date=$(git log -1 --format=%cd --date=format:'%Y/%m/%d')" >> $GITHUB_OUTPUT
          echo "commit_message=$(git log -1 --pretty=%B)" >> $GITHUB_OUTPUT
          echo "commit_author=$(git log -1 --pretty=%an)" >> $GITHUB_OUTPUT

      - name: Create commit info JSON
        run: |
          mkdir -p docs
          cat > docs/commit-info.json << EOF
          {
            "hash": "${{ steps.commit.outputs.commit_hash }}",
            "date": "${{ steps.commit.outputs.commit_date }}",
            "message": "${{ steps.commit.outputs.commit_message }}",
            "author": "${{ steps.commit.outputs.commit_author }}"
          }
          EOF

      - name: Install jq
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Download latest stable.json from hackCraft2-public
        run: |
          echo "Fetching latest stable release..."
          tag=$(curl -s https://api.github.com/repos/0x48lab/hackCraft2-public/releases \
            | jq -r '[.[] | select(.tag_name | startswith("stable-"))] | sort_by(.published_at) | reverse | .[0].tag_name')

          echo "Latest stable tag: $tag"

          # ダウンロードと整形
          curl -sL -o docs/stable_raw.json https://github.com/0x48lab/hackCraft2-public/releases/download/$tag/stable.json

          # 情報整形して stable.json に保存
          jq -n \
            --arg tag "$tag" \
            --argjson raw "$(cat docs/stable_raw.json)" \
            '{
              build_number: ($tag | sub("stable-"; "") | tonumber),
              version: "develop",
              release_date: now | strftime("%Y-%m-%dT%H:%M:%SZ"),
              download_url: "https://github.com/0x48lab/hackCraft2-public/releases/download/\($tag)/hackCraft2-all.jar",
              source_commit_hash: $raw.source_commit_hash,
              public_commit_hash: $raw.public_commit_hash,
              paper_version: $raw.paper_version,
              release_tag: $tag
            }' > docs/stable.json

          rm docs/stable_raw.json

      - name: Add cache control headers
        run: |
          cat > docs/_headers << EOF
          /*
            Cache-Control: no-cache, no-store, must-revalidate
            Pragma: no-cache
            Expires: 0
          EOF

      - name: List generated files
        run: |
          echo "Contents of docs directory:"
          ls -la docs/
          echo "\nContents of stable.json:"
          cat docs/stable.json

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './docs'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
